### ISSUE TITLE
Callback & loadUrlDrawable

### ISSUE THREAD

**Issue by Swiip** [koush/UrlImageViewHelper#30]
I really enjoy your lib but I'm facing a problem while using UrlImageViewHelper.loadUrlDrawable with a callback. The callback was fired only when the image was in cache.

I dig a little in the code and found that in the Runnable "completion" in UrlImageViewHelper.java line 500, the callback is launched only if there is at least on imageview which there is not in my case.

I'm not sure if it's the cleanest way to fix this but I added this lines at the end of the Runnable:

``` java
if(downloads.size() == 0 && callback != null) {
    callback.onLoaded(null, loader.result, url, false);
}
```

**Comment by koush** [comment]
Admittedly, the callback code hasn't been very well tested. I'll take a look and fix the problem. Thanks!

**Comment by koush** [comment]
This should be fixed in https://github.com/koush/UrlImageViewHelper/commit/4e38361337a6e167e3409c99dc6ec8c01e80c4a4.

It also fixed where the callback could erroneously be called multiple times for ImageViews that are waiting on the same url. It will only call the callback on the ImageView that requested it.
