### ISSUE TITLE
Using with a RemoteViews object?

### ISSUE THREAD

**Issue by awnry** [koush/UrlImageViewHelper#50]
Sorry if I'm posting this in the wrong location; I'm kind of new to the social part of GitHub. :)

Anyway, I've been using UrlImageViewHelper in the ListFragments in my News & Weather app with great success (kudos on what you've done, it's a great helper!)

But now I'm trying to get it to work with an AppWidgetProvider, where there is no ImageView available. Instead, images are set on the AppWidgetProvider's RemoteViews object using the setImageViewBitmap(), setImageViewResource(), and setImageViewUri() methods.

Is there a way to utilize UrlImageViewHelper with a RemoteViews, perhaps adding a new method like:

UrlImageViewHelper.setRemoteViewsUriDrawable(remoteViews, R.id.some_widget_icon, "http://www.example.com/some/image/url.png") ??

Any ideas here? Thanks!!!

**Comment by koush** [comment]
Use loadUrlDrawable and then in the callback, use RemoteViews.setBitmap.

Can't really do what you want; the RemoteViews API has more to it than regular views... gotta send it over to the Remote view host, etc. Would require more information than URLImageViewHelper has available to it.

**Comment by awnry** [comment]
Oh, okay... I didn't even know about the UrlImageViewCallback class and the associated loadUrlDrawable() method. Thanks! This is exactly what I was looking for. I will have to update the widget thru the AppWidgetManager using the updated RemoteViews (like you said, "gotta send it over to the Remote view host") but this is fine. I think it will work perfectly.

Could you clarify something though? What exactly are the Image and Drawable parameters to the UrlImageViewCallback.onLoaded() method? And am I correct in assuming that I can retrieve the loaded image Bitmap from ImageView.getDrawingCache()? If not, what is the correct way to obtain the loaded Bitmap in the onLoaded() method?

Thanks for your help!

**Comment by koush** [comment]
What you want is the BitmapDrawable that was loaded, and then get the Bitmap out of that.

After you get an onLoaded event, you get the Drawable  that was loaded. Unfortunately, this is never castable to a BitmapDrawable. This is due to how the underpinnings of this library works... it wraps the drawable with its own drawable (ZombieDrawable) to watch for garbage collection events.

So what you can do instead is call getImmediateMutableDrawable inside the onLoaded event. Then cast that to a BitmapDrawable. Then get the bitmap out of that. I'd still check this with an instanceof before casting it, just in case.

**Comment by koush** [comment]
I think I need to update the library to provide direct access to the bitmaps, as I don't think caching BitmapDrawables is appropriate.

But my suggestion above will work.

**Comment by awnry** [comment]
Makes perfect sense -- thanks again!
